### ISSUE TITLE
The code doesn't work in SDK:2.5.0

### ISSUE THREAD

**Issue by mesqr** [nippur72/SqlServerSocket#2]
The Code of ClientSide doesn't work in Dart SDK:2.5.0
i tried to fix some of it but i couldn't make it work.
Could you update fix it ,please ?

**Comment by narcisrotllant1** [comment]
after a few days of headache have been able to make it work, who problem do you have?

**Comment by ijaznaeem** [comment]
on open following error 
Unhandled exception:
LateInitializationError: Field '_completer@19341813' has not been initialized.
#0      SqlConnection._completer (package:sqlapp/sqlconnection.dart)
#1      SqlConnection._receiveData (package:sqlapp/sqlconnection.dart:276:9)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#5      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#6      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#7      _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#8      _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#25     _StreamController.add (dart:async/stream_controller.dart:554:5)
#26     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#27     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
